// This is a Vercel serverless function.
// It handles file uploads from the client and stores them in Vercel Blob.

import { handleUpload } from '@vercel/blob/client';

export const config = {
  api: {
    // Vercel's helper needs the raw body, so we disable the default parser.
    bodyParser: false,
  },
};

export default async function handler(request, response) {
  // We only allow POST requests to this endpoint.
  if (request.method !== 'POST') {
    response.setHeader('Allow', 'POST');
    return response.status(405).end('Method Not Allowed');
  }

  try {
    // The `handleUpload` function from `@vercel/blob/client` handles the entire upload process.
    // It securely generates a token for the client to upload the file directly to Vercel Blob.
    const jsonResponse = await handleUpload({
      body: request.body,
      request,
      // This function runs on the server before a token is generated.
      // It's a good place to add validation or metadata.
      onBeforeGenerateToken: async (pathname /*, clientPayload */) => {
        return {
          // Add a random suffix to the filename to prevent overwriting existing files.
          addRandomSuffix: true,
          // You can limit the allowed content types here.
          allowedContentTypes: [
            // Images
            'image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/heic', 'image/heif',
            // Videos
            'video/mp4', 'video/quicktime', 'video/webm', 'video/ogg', 
            'video/x-msvideo', // AVI
            'video/x-ms-wmv',   // WMV
            'video/x-matroska', // MKV
            // Audio
            'audio/mpeg'
          ],
          // The token is automatically generated by Vercel Blob unless you provide one.
          // The Vercel project integration will automatically set the BLOB_READ_WRITE_TOKEN.
        };
      },
      // This function runs on the server after the upload is complete.
      onUploadCompleted: async ({ blob, tokenPayload }) => {
        console.log('Blob upload completed successfully', blob.url);
        // Here you could, for example, write to your database.
      },
    });

    // Return the response from Vercel Blob to the client.
    return response.status(200).json(jsonResponse);

  } catch (error) {
    console.error('Error during upload:', error);
    return response.status(500).json({ error: error.message });
  }
}